[project]
name = "sferum-bot"
version = "0.1.2"
dependencies = [
    "aiogram==3.22.0",
    "loguru==0.7.3",
    "pydantic-settings>=2.10.1",
]

[tool.ruff]
select = ["ALL"]
ignore = [
    "BLE001", "PLR2004", "PLE0604"
]
